#!/bin/bash

# Usage Example:
#
# Either way, w or w/o quotes
# $ vi_ name of file.txt
# $ vi_ 'name of file.txt'
#
# $ ls 
# name_of_file.txt
# 
# Starts vim with the supplied string as the 
# file name replacing spaces with underscores

strWithSpace="${*}"
vim "${strWithSpace// /_}"

